### ISSUE TITLE
Omit vendor prefixes

### ISSUE THREAD

**Issue by KittyGiraudel** [KevinPy/Flexo#1]
Most pipelines include Autoprefixer, and it is not Flexo’s responsibility to add vendor prefixes. I’d argue you should remove them altogether, or at least provide a prefix-less version.

**Comment by KevinPy** [comment]
I thought the same thing before release Flexo. I'll do an update soon. Thank you for your comment.

**Comment by ch-stuart** [comment]
Fwiw, autoprefixer will remove and adjust vendor prefixes as needed based on the browser support configuration you pass to it. In other words, if you leave them in, autoprefixer will still work just fine.
