### ISSUE TITLE
Please publish Flexo on bower & npm

### ISSUE THREAD

**Issue by debloper** [KevinPy/Flexo#2]
Yes, it's radically easy to download and use the minified css file, but I'd rather prefer if it's not part of "my" code for 2 reasons:
- I didn't write the code and there's no viable way to give attribution, so it feels like a plagiarism (on top, there's no license information as well)
- I'd want it to be on the latest version, and not have to redownload manually (and have an unnecessary git-diff of a one-line-minified-css file to handle)

Having the project on the bower/npm registry ensures both these problems are handled, along with a better way of installing/managing it as a 3rd party library

This is a nifty little tool that focuses on solving one problem, and I really like it for that.

P.S: if you won't mind me writing the `bower.json` & `package.json` for registering it, I can send a pull request. I'd need to know which license you'd want for the project to create those descriptor files (personal opinion, MIT license suits best for this project).

**Comment by KevinPy** [comment]
Done.
